name: Deploy to Docker Registry
on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Docker image tag (e.g., v1.2.3)'
        required: true
        default: 'latest'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Set up Node.js and pnpm
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: install deps
        run: |
          pnpm install
          NEXT_PRIVATE_STANDALONE=true pnpm run build
      - name: Copy build output to Docker context
        run: |
          mkdir dist
          cp -a .next/standalone/. dist/
          cp -a .next/static dist/
          cp -r public dist/
          cp package.json dist/
          cp README.md dist/
          pnpm install --prod
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./dist
          file: Dockerfile.ci
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/fsrs-online-training:${{ inputs.version || github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
